FROM python:3.10-slim

COPY ./requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLASK_APP=app/server.py
ENV FLASK_ENV=development
# cause flask to restart on changes
ENV FLASK_DEBUG=1

CMD [ "flask", "run" , "--host", "0.0.0.0" ]
